# Generated by Django 4.1 on 2023-04-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimendions',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='gross_weight',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_weight',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_per_box',
            field=models.CharField(max_length=50),
        ),
    ]
