# Generated by Django 4.1 on 2023-04-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_dimendions_alter_product_gross_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bracode_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimendions',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gross_weight',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_weight',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_per_box',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
