# Generated by Django 4.1 on 2023-04-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_brand_delete_author_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_name',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_category',
        ),
    ]
