# Generated by Django 4.1 on 2023-04-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
