# Generated by Django 4.1 on 2023-04-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_model',
            new_name='product_code',
        ),
    ]
